### ISSUE TITLE
Fix code typo

### ISSUE THREAD

**Issue by mshinh** [owjs3901/SSU_World#1]
I would like to fix this typo error
https://github.com/owjs3901/SSU_World/blob/912553157aee2efc70b655b3eb8e9e41a1b4863f/public/signup.html#L129

**Comment by mshinh** [comment]
Hey @owjs3901  Can you label this issue as hacktoberfest2020 ? Actually, it is part of my school assignment to submit PRs to solve issues in open source project while participating in Hacktoberfest. 
Thankyou

**Comment by owjs3901** [comment]
Hello @Shinh18 I thought about your request. As a result I add tag of <hacktoberfest2020> at this issue.
Is this the result you want?
